import dependencyMap from '../../assets/ime/dependency-map.json';
import schemaFiles from '../../assets/ime/schema-files.json';
import schemaName from '../../assets/ime/schema-name.json';
import schemaTarget from '../../assets/ime/schema-target.json';
import targetFiles from '../../assets/ime/target-files.json';
import { fsOperate } from './fs';
import { ImeDB } from './indexdb';
import { control, expose } from './worker-box';

import rimeData from './rime.data?url';
import rimeWasmWrapper from './rime.js?url';
import rimeWasm from './rime.wasm?url';

const RIME_USER = '/rime';
const RIME_SHARED = '/usr/share/rime-data';

// rime.js types
declare const Module: any;
declare const IDBFS: any;

/**
 * Loads wasm generated by emscripten.
 *
 * @param script - The name of js wrapper.
 * @param options.url - The URL prefix of files if use CDN.
 * @param options.init - The function to execute before promise resolved.
 * @param options.Module - The customized Module object.
 * @returns A promise that is resolved when wasm is loaded.
 */
function loadWasm(options?: {
  url?: string;
  init?: () => Promise<void> | void;
  Module?: { [key: string]: (...args: any[]) => any };
}) {
  options = options || {};
  const { url, init } = options;
  return new Promise(async (resolve) => {
    self.Module = {
      ...options?.Module,
      // @ts-ignore
      async onRuntimeInitialized() {
        init && (await init());
        resolve(null);
      },
      locateFile(path: string, prefix: string) {
        switch (path) {
          case 'rime.data':
            return rimeData;
          case 'rime.wasm':
            return rimeWasm;
          default:
            return (url || prefix) + path;
        }
      },
    };
    const rime = await fetch(rimeWasmWrapper);
    const text = await rime.text();
    new Function(text).call(self);
  });
}

function getURL(target: string, name: string) {
  // if ('__RIME_CDN__') {
  //   return '__RIME_CDN__' + `${target}@${(targetVersion as {[key: string]: string})[target]}/${name}`
  // }
  return new URL(`/src/assets/ime/${target}/${name}`, import.meta.url).href;
}

const lazyCache = new ImeDB('ime');

async function fetchPrebuilt(schemaId: string) {
  const fetched: string[] = [];
  function getFiles(key: string) {
    if (fetched.includes(key)) {
      return [];
    }
    fetched.push(key);
    const files: {
      name: string;
      md5: string;
      target: string;
    }[] = [];

    // @ts-ignore
    for (const dependency of dependencyMap[key] || []) {
      files.push(...getFiles(dependency));
    }
    // @ts-ignore
    const { dict, prism } = schemaFiles[key];
    const dictionary = dict || key;
    const tableBin = `${dictionary}.table.bin`;
    const reverseBin = `${dictionary}.reverse.bin`;
    const prismBin = `${prism || dictionary}.prism.bin`;
    const schemaYaml = `${key}.schema.yaml`;
    const target = (schemaTarget as { [key: string]: string })[key];
    for (const fileName of [tableBin, reverseBin, prismBin, schemaYaml]) {
    // @ts-ignore
      for (const { name, md5 } of targetFiles[target]) {
        if (fileName === name) {
          files.push({ name, md5, target });
          break;
        }
      }
    }
    return files;
  }
  const files = getFiles(schemaId);
  await Promise.all(
    files.map(async ({ name, target, md5 }) => {
      const path = `${RIME_SHARED}/build/${name}`;
      try {
        Module.FS.lookupPath(path);
      } catch (e) {
        // not exists
        const ab = await lazyCache.get(name, md5, getURL(target, name));
        Module.FS.writeFile(path, new Uint8Array(ab));
      }
    }),
  );
}

async function setIME(schemaId: string) {
  if (!deployed) {
    await fetchPrebuilt(schemaId);
  }
  Module.ccall('set_ime', 'null', ['string'], [schemaId]);
  return syncUserDirectory('write');
}

function syncUserDirectory(direction: 'read' | 'write') {
  let resolve: (_: any) => void;
  let reject: (err: any) => void;
  const promise = new Promise<void>((_resolve, _reject) => {
    resolve = _resolve;
    reject = _reject;
  });
  Module.FS.syncfs(direction === 'read', (err: any) => {
    if (err) {
      reject(err);
    }
    resolve(null);
  });
  return promise;
}

const printError = control<(level: string, message: string) => void>('printError');
const readyPromise = loadWasm({
  url: '',
  async init() {
    Module.FS.mkdir(RIME_USER);
    Module.FS.mount(IDBFS, {}, RIME_USER);
    await syncUserDirectory('read');
    Module.ccall('init', 'null', [], []);
    for (const [schema, name] of Object.entries(schemaName)) {
      Module.ccall('set_schema_name', 'null', ['string', 'string'], [schema, name]);
    }
  },
  Module: {
    // Customize for glog
    printErr(message) {
      const match = message.match(/[EWID]\S+ \S+ \S+ (.*)/);
      if (match) {
        printError(
          // @ts-ignore
          {
            E: 'error',
            W: 'warn',
            I: 'info',
            D: 'debug',
          }[message[0]],
          match[1],
        );
      } else {
        console.error(message);
      }
    },
  },
});

let deployed = false;
const deployStatus = control('deployStatus');
// @ts-ignore
globalThis._deployStatus = (status: 'start' | 'failure' | 'success', schemas: string) => {
  // called from api.cpp
  if (status === 'success') {
    deployed = true;
  }
  deployStatus(status, schemas);
};

function rmStar(path: string) {
  for (const file of Module.FS.readdir(path)) {
    if (file === '.' || file === '..') {
      continue;
    }
    const subPath = `${path}/${file}`;
    const { mode } = Module.FS.lstat(subPath);
    if (Module.FS.isDir(mode)) {
      rmStar(subPath);
      Module.FS.rmdir(subPath);
    } else {
      Module.FS.unlink(subPath);
    }
  }
}

async function resetUserDirectory() {
  rmStar(RIME_USER);
  await syncUserDirectory('write');
  deployed = false;
  Module.ccall('reset', 'null', [], []);
}

expose(
  {
    fsOperate,
    resetUserDirectory,
    setIME,
    setOption(option: string, value: boolean) {
      return Module.ccall('set_option', 'null', ['string', 'number'], [option, value]);
    },
    setPageSize(size: number) {
      return Module.ccall('set_page_size', 'null', ['number'], [size]);
    },
    deploy() {
      return Module.ccall('deploy', 'null', [], []);
    },
    async process(input) {
      const result = JSON.parse(Module.ccall('process', 'string', ['string'], [input]));
      if ('committed' in result) {
        await syncUserDirectory('write'); // record frequency
      }
      return result;
    },
    selectCandidateOnCurrentPage(index: number) {
      return Module.ccall('select_candidate_on_current_page', 'string', ['number'], [index]);
    },
    changePage(backward: boolean) {
      return Module.ccall('change_page', 'string', ['boolean'], [backward]);
    },
  },
  readyPromise,
);
